imports:
    - { resource: config.yml }

framework:
    validation:
        cache: '%validation_cache%'

doctrine:
    orm:
        metadata_cache_driver: '%doctrine_cache%'
        result_cache_driver: '%doctrine_cache%'
        query_cache_driver: '%doctrine_cache%'
